name: C/C++ CI

on:
  push:
    branches: [ master, multi-user ]
  pull_request:
    branches: [ master, multi-user ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: bash compile.sh
